version: "3.4"

services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
    restart: unless-stopped
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3001:3306
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: votes
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  govote:
    depends_on:
      - db
    image: go-vote
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 3000
      DB_HOST: db:3306
      DB_DATABASE: votes
      DB_USER: root
      DB_PASSWORD: root
      AUTH_USER: admin
      AUTH_PASS: admin
    ports:
      - 3000:3000
volumes:
  db_data: {}
