version: "3.4"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3001:3306
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: votes
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  # govote:
  #   depends_on:
  #     - db
  #   image: go-vote
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     DB_HOST: db:3306
  #     DB_DATABASE: votes
  #     DB_USER: root
  #     DB_PASSWORD: root
  #   ports:
  #     - 3000:3000
volumes:
  db_data: {}
